### ISSUE TITLE
compilation issue in  tensorflow Benchmark Models in aws f1 instance,Xilinx ML suite from marketplace.

### ISSUE THREAD

**Issue by Harikrishnah007** [Xilinx/ml-suite#102]
I am facing issue in Quantize for inference steps.
i am trying to run command python run.py --quantize --model /opt/models/tensorflow/inception_v1_baseline.pb --output_dir work --input_nodes data --output_nodes loss3_loss3 --input_shapes ?,224,224,3

getting following issues

XDNN library .so file None not found
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    from xfdnn.rt.xdnn_rt_tf import TFxdnnRT as xdnnRT
  File "/opt/ml-suite/examples/tensorflow/xfdnn/rt/xdnn_rt_tf.py", line 19, in <module>
    from xfdnn.rt.xdnn_opt import CPUTransform, HWEmuTransform, FPGATransform
  File "/opt/ml-suite/examples/tensorflow/xfdnn/rt/xdnn_opt.py", line 26, in <module>
    from xfdnn.tools.emu.factory          import factory as _factory
ImportError: No module named emu.factory

Thank you

**Comment by ilansw** [comment]
Was this issue resolved?
