### ISSUE TITLE
face detect app issue in U250 

### ISSUE THREAD

**Issue by mahinlma** [Xilinx/ml-suite#98]
getting error while running face detect app in alveo-u250 :

Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "mp_video.py", line 210, in detect_forward
    det = run_fpga.RunFPGA(param_str)
  File "/home/test/Mahi/ml/apps/face_detect/run_fpga.py", line 17, in __init__
    ret, handles = xdnn.createHandle(self._args["xclbin"], "kernelSxdnn_0")
AttributeError: 'module' object has no attribute 'createHandle'

**Comment by wilderfield** [comment]
Try :

cd apps/face_detect

source ../../overlaybins/setup.sh


It should work. However, I remember it being a bit painful to get the video
to display on the host using X11 forwarding between container and host os.
However I know I ran it.
